{
  "formatVersion": "1.1",
  "component": {
    "group": "io.wf9a5m75",
    "module": "redis-android",
    "version": "1.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "redis-android-1.1.6.aar",
          "url": "redis-android-1.1.6.aar",
          "size": 2339700,
          "sha512": "5848839c4e273c7453de8f7f1a622f5171452042169071341c6a56e3fbee3fe7de6e70d5ee066f21c639ec34fb7463d5c0cd3dcfe02ee8fdc68a573edce90326",
          "sha256": "8875cb528265a7e223337c0dac4bb28546fe2a487489aa3f8fecb7e47ea9089b",
          "sha1": "e4ff5bafa67495ffee923810f5c7967ba42d1701",
          "md5": "28c97c89d9642ccca4112132bdf681d5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "redis-android-1.1.6.aar",
          "url": "redis-android-1.1.6.aar",
          "size": 2339700,
          "sha512": "5848839c4e273c7453de8f7f1a622f5171452042169071341c6a56e3fbee3fe7de6e70d5ee066f21c639ec34fb7463d5c0cd3dcfe02ee8fdc68a573edce90326",
          "sha256": "8875cb528265a7e223337c0dac4bb28546fe2a487489aa3f8fecb7e47ea9089b",
          "sha1": "e4ff5bafa67495ffee923810f5c7967ba42d1701",
          "md5": "28c97c89d9642ccca4112132bdf681d5"
        }
      ]
    }
  ]
}
